#!/usr/bin/env python3
import subprocess
import json
import sys
import os
import subprocess
import argparse


def _error(msg):
    sys.stderr.write('{}\n'.format(msg))
    sys.exit(1)


cl_parser = argparse.ArgumentParser(description='Run Node server')
cl_parser.add_argument(
    '--debug', '-d', help='Debug through node-inspector', action='store_true',
    default=False,
)
args = cl_parser.parse_args()

if not args.debug:
    node_command = ['./node_modules/.bin/babel-node', '.', ]
else:
    node_command = [
        './node_modules/.bin/babel-node', '--inspect', '--debug-brk', '.',
    ]

try:
    subprocess.check_call(node_command)
except subprocess.CalledProcessError:
    _error('Node failed')
except KeyboardInterrupt:
    sys.exit(0)
